[api_keys]
BLS_API_KEY = "60239f8eca874ce8be93238a358c4c09"

[database]
DATABASE_URL = "postgresql://neondb_owner:npg_piUoXLSw9ZC7@ep-curly-morning-a5ww5ryr-pooler.us-east-2.aws.neon.tech/jobriskai?sslmode=require"  # Add your Neon PostgreSQL URL if not already configured
